//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.11 at 07:13:21 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fatturapa.gov.it/sdi/fatturapa/v1.1")
package it.infn.fe.generati.fatt;
